name: Node.js CI

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
        npm ci
        npm run build --if-present
    - uses: actions/upload-artifact@master
      with:
        name: build-artifact
        path: build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - uses: actions/download-artifact@master
      with:
        name: build-artifact
        path: build 
    - name: Deploy with SCP
      uses: ./.github/actions/scp-deploy
      with:
        target: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        host-path: 'build'
        target-dest: ${{ secrets.TARGET }}
        replace: true

